// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/network/messages.proto

package network

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_UNKNOWN         MsgType = 0
	MsgType_JOIN_TABLE      MsgType = 1
	MsgType_PLAYER_READY    MsgType = 2
	MsgType_SHUFFLE_STEP    MsgType = 3
	MsgType_SHUFFLE_COMMIT  MsgType = 4
	MsgType_PARTIAL_DECRYPT MsgType = 5
	MsgType_PLAYER_ACTION   MsgType = 6
	MsgType_GAME_STATE_SYNC MsgType = 7
	MsgType_HEARTBEAT       MsgType = 8
	MsgType_TIMEOUT_VOTE    MsgType = 9
	MsgType_HAND_RESULT     MsgType = 10
	MsgType_LEAVE_TABLE     MsgType = 11
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "JOIN_TABLE",
		2:  "PLAYER_READY",
		3:  "SHUFFLE_STEP",
		4:  "SHUFFLE_COMMIT",
		5:  "PARTIAL_DECRYPT",
		6:  "PLAYER_ACTION",
		7:  "GAME_STATE_SYNC",
		8:  "HEARTBEAT",
		9:  "TIMEOUT_VOTE",
		10: "HAND_RESULT",
		11: "LEAVE_TABLE",
	}
	MsgType_value = map[string]int32{
		"UNKNOWN":         0,
		"JOIN_TABLE":      1,
		"PLAYER_READY":    2,
		"SHUFFLE_STEP":    3,
		"SHUFFLE_COMMIT":  4,
		"PARTIAL_DECRYPT": 5,
		"PLAYER_ACTION":   6,
		"GAME_STATE_SYNC": 7,
		"HEARTBEAT":       8,
		"TIMEOUT_VOTE":    9,
		"HAND_RESULT":     10,
		"LEAVE_TABLE":     11,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_network_messages_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_internal_network_messages_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_internal_network_messages_proto_rawDescGZIP(), []int{0}
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MsgType                `protobuf:"varint,1,opt,name=type,proto3,enum=network.MsgType" json:"type,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_internal_network_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_internal_network_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_UNKNOWN
}

func (x *Envelope) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Envelope) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type JoinTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	BuyIn         int64                  `protobuf:"varint,3,opt,name=buy_in,json=buyIn,proto3" json:"buy_in,omitempty"`
	SraPubKeyE    []byte                 `protobuf:"bytes,4,opt,name=sra_pub_key_e,json=sraPubKeyE,proto3" json:"sra_pub_key_e,omitempty"`
	SessionNonce  []byte                 `protobuf:"bytes,5,opt,name=session_nonce,json=sessionNonce,proto3" json:"session_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinTable) Reset() {
	*x = JoinTable{}
	mi := &file_internal_network_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTable) ProtoMessage() {}

func (x *JoinTable) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTable.ProtoReflect.Descriptor instead.
func (*JoinTable) Descriptor() ([]byte, []int) {
	return file_internal_network_messages_proto_rawDescGZIP(), []int{1}
}

func (x *JoinTable) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *JoinTable) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *JoinTable) GetBuyIn() int64 {
	if x != nil {
		return x.BuyIn
	}
	return 0
}

func (x *JoinTable) GetSraPubKeyE() []byte {
	if x != nil {
		return x.SraPubKeyE
	}
	return nil
}

func (x *JoinTable) GetSessionNonce() []byte {
	if x != nil {
		return x.SessionNonce
	}
	return nil
}

type PlayerReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum       int64                  `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerReady) Reset() {
	*x = PlayerReady{}
	mi := &file_internal_network_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReady) ProtoMessage() {}

func (x *PlayerReady) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReady.ProtoReflect.Descriptor instead.
func (*PlayerReady) Descriptor() ([]byte, []int) {
	return file_internal_network_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerReady) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *PlayerReady) GetHandNum() int64 {
	if x != nil {
		return x.HandNum
	}
	return 0
}

type ShuffleStep struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TableId         string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum         int64                  `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	PlayerId        string                 `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Deck            [][]byte               `protobuf:"bytes,4,rep,name=deck,proto3" json:"deck,omitempty"`
	CommitmentHash  []byte                 `protobuf:"bytes,5,opt,name=commitment_hash,json=commitmentHash,proto3" json:"commitment_hash,omitempty"`
	CommitmentNonce []byte                 `protobuf:"bytes,6,opt,name=commitment_nonce,json=commitmentNonce,proto3" json:"commitment_nonce,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShuffleStep) Reset() {
	*x = ShuffleStep{}
	mi := &file_internal_network_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShuffleStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShuffleStep) ProtoMessage() {}

func (x *ShuffleStep) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShuffleStep.ProtoReflect.Descriptor instead.
func (*ShuffleStep) Descriptor() ([]byte, []int) {
	return file_internal_network_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ShuffleStep) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *ShuffleStep) GetHandNum() int64 {
	if x != nil {
		return x.HandNum
	}
	return 0
}

func (x *ShuffleStep) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ShuffleStep) GetDeck() [][]byte {
	if x != nil {
		return x.Deck
	}
	return nil
}

func (x *ShuffleStep) GetCommitmentHash() []byte {
	if x != nil {
		return x.CommitmentHash
	}
	return nil
}

func (x *ShuffleStep) GetCommitmentNonce() []byte {
	if x != nil {
		return x.CommitmentNonce
	}
	return nil
}

type ShuffleCommit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TableId        string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum        int64                  `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	PlayerId       string                 `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	CommitmentHash []byte                 `protobuf:"bytes,4,opt,name=commitment_hash,json=commitmentHash,proto3" json:"commitment_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShuffleCommit) Reset() {
	*x = ShuffleCommit{}
	mi := &file_internal_network_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShuffleCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShuffleCommit) ProtoMessage() {}

func (x *ShuffleCommit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShuffleCommit.ProtoReflect.Descriptor instead.
func (*ShuffleCommit) Descriptor() ([]byte, []int) {
	return file_internal_network_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ShuffleCommit) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *ShuffleCommit) GetHandNum() int64 {
	if x != nil {
		return x.HandNum
	}
	return 0
}

func (x *ShuffleCommit) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ShuffleCommit) GetCommitmentHash() []byte {
	if x != nil {
		return x.CommitmentHash
	}
	return nil
}

type ZKProofWire struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             []byte                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             []byte                 `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	S             []byte                 `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`
	H             []byte                 `protobuf:"bytes,4,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZKProofWire) Reset() {
	*x = ZKProofWire{}
	mi := &file_internal_network_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZKProofWire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZKProofWire) ProtoMessage() {}

func (x *ZKProofWire) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZKProofWire.ProtoReflect.Descriptor instead.
func (*ZKProofWire) Descriptor() ([]byte, []int) {
	return file_internal_network_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ZKProofWire) GetA() []byte {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *ZKProofWire) GetB() []byte {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *ZKProofWire) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *ZKProofWire) GetH() []byte {
	if x != nil {
		return x.H
	}
	return nil
}

type PartialDecrypt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum       int64                  `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	PlayerId      string                 `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	CardIndex     int32                  `protobuf:"varint,4,opt,name=card_index,json=cardIndex,proto3" json:"card_index,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,5,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Result        []byte                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	Proof         *ZKProofWire           `protobuf:"bytes,7,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartialDecrypt) Reset() {
	*x = PartialDecrypt{}
	mi := &file_internal_network_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialDecrypt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialDecrypt) ProtoMessage() {}

func (x *PartialDecrypt) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialDecrypt.ProtoReflect.Descriptor instead.
func (*PartialDecrypt) Descriptor() ([]byte, []int) {
	return file_internal_network_messages_proto_rawDescGZIP(), []int{6}
}

func (x *PartialDecrypt) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *PartialDecrypt) GetHandNum() int64 {
	if x != nil {
		return x.HandNum
	}
	return 0
}

func (x *PartialDecrypt) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PartialDecrypt) GetCardIndex() int32 {
	if x != nil {
		return x.CardIndex
	}
	return 0
}

func (x *PartialDecrypt) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *PartialDecrypt) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PartialDecrypt) GetProof() *ZKProofWire {
	if x != nil {
		return x.Proof
	}
	return nil
}

type PlayerAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum       int64                  `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	PlayerId      string                 `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Action        int32                  `protobuf:"varint,4,opt,name=action,proto3" json:"action,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Seq           int64                  `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAction) Reset() {
	*x = PlayerAction{}
	mi := &file_internal_network_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAction) ProtoMessage() {}

func (x *PlayerAction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAction.ProtoReflect.Descriptor instead.
func (*PlayerAction) Descriptor() ([]byte, []int) {
	return file_internal_network_messages_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerAction) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *PlayerAction) GetHandNum() int64 {
	if x != nil {
		return x.HandNum
	}
	return 0
}

func (x *PlayerAction) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerAction) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *PlayerAction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PlayerAction) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type GameStateSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum       int64                  `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	Phase         int32                  `protobuf:"varint,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Pot           int64                  `protobuf:"varint,4,opt,name=pot,proto3" json:"pot,omitempty"`
	CurrentBet    int64                  `protobuf:"varint,5,opt,name=current_bet,json=currentBet,proto3" json:"current_bet,omitempty"`
	ActionPlayer  string                 `protobuf:"bytes,6,opt,name=action_player,json=actionPlayer,proto3" json:"action_player,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,7,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ActionLog     [][]byte               `protobuf:"bytes,8,rep,name=action_log,json=actionLog,proto3" json:"action_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateSync) Reset() {
	*x = GameStateSync{}
	mi := &file_internal_network_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateSync) ProtoMessage() {}

func (x *GameStateSync) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateSync.ProtoReflect.Descriptor instead.
func (*GameStateSync) Descriptor() ([]byte, []int) {
	return file_internal_network_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GameStateSync) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *GameStateSync) GetHandNum() int64 {
	if x != nil {
		return x.HandNum
	}
	return 0
}

func (x *GameStateSync) GetPhase() int32 {
	if x != nil {
		return x.Phase
	}
	return 0
}

func (x *GameStateSync) GetPot() int64 {
	if x != nil {
		return x.Pot
	}
	return 0
}

func (x *GameStateSync) GetCurrentBet() int64 {
	if x != nil {
		return x.CurrentBet
	}
	return 0
}

func (x *GameStateSync) GetActionPlayer() string {
	if x != nil {
		return x.ActionPlayer
	}
	return ""
}

func (x *GameStateSync) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *GameStateSync) GetActionLog() [][]byte {
	if x != nil {
		return x.ActionLog
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum       int64                  `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_network_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_network_messages_proto_rawDescGZIP(), []int{9}
}

func (x *Heartbeat) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *Heartbeat) GetHandNum() int64 {
	if x != nil {
		return x.HandNum
	}
	return 0
}

func (x *Heartbeat) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type TimeoutVote struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TableId         string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum         int64                  `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	VotingPlayerId  string                 `protobuf:"bytes,3,opt,name=voting_player_id,json=votingPlayerId,proto3" json:"voting_player_id,omitempty"`
	TimeoutPlayerId string                 `protobuf:"bytes,4,opt,name=timeout_player_id,json=timeoutPlayerId,proto3" json:"timeout_player_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TimeoutVote) Reset() {
	*x = TimeoutVote{}
	mi := &file_internal_network_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutVote) ProtoMessage() {}

func (x *TimeoutVote) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutVote.ProtoReflect.Descriptor instead.
func (*TimeoutVote) Descriptor() ([]byte, []int) {
	return file_internal_network_messages_proto_rawDescGZIP(), []int{10}
}

func (x *TimeoutVote) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *TimeoutVote) GetHandNum() int64 {
	if x != nil {
		return x.HandNum
	}
	return 0
}

func (x *TimeoutVote) GetVotingPlayerId() string {
	if x != nil {
		return x.VotingPlayerId
	}
	return ""
}

func (x *TimeoutVote) GetTimeoutPlayerId() string {
	if x != nil {
		return x.TimeoutPlayerId
	}
	return ""
}

type HandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	HandNum       int64                  `protobuf:"varint,2,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	Pots          []*PotResult           `protobuf:"bytes,3,rep,name=pots,proto3" json:"pots,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandResult) Reset() {
	*x = HandResult{}
	mi := &file_internal_network_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandResult) ProtoMessage() {}

func (x *HandResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandResult.ProtoReflect.Descriptor instead.
func (*HandResult) Descriptor() ([]byte, []int) {
	return file_internal_network_messages_proto_rawDescGZIP(), []int{11}
}

func (x *HandResult) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *HandResult) GetHandNum() int64 {
	if x != nil {
		return x.HandNum
	}
	return 0
}

func (x *HandResult) GetPots() []*PotResult {
	if x != nil {
		return x.Pots
	}
	return nil
}

func (x *HandResult) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

type PotResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	WinnerIds     []string               `protobuf:"bytes,2,rep,name=winner_ids,json=winnerIds,proto3" json:"winner_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PotResult) Reset() {
	*x = PotResult{}
	mi := &file_internal_network_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PotResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PotResult) ProtoMessage() {}

func (x *PotResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PotResult.ProtoReflect.Descriptor instead.
func (*PotResult) Descriptor() ([]byte, []int) {
	return file_internal_network_messages_proto_rawDescGZIP(), []int{12}
}

func (x *PotResult) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PotResult) GetWinnerIds() []string {
	if x != nil {
		return x.WinnerIds
	}
	return nil
}

var File_internal_network_messages_proto protoreflect.FileDescriptor

const file_internal_network_messages_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/network/messages.proto\x12\anetwork\"\xb5\x01\n" +
	"\bEnvelope\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.network.MsgTypeR\x04type\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"\xa6\x01\n" +
	"\tJoinTable\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x15\n" +
	"\x06buy_in\x18\x03 \x01(\x03R\x05buyIn\x12!\n" +
	"\rsra_pub_key_e\x18\x04 \x01(\fR\n" +
	"sraPubKeyE\x12#\n" +
	"\rsession_nonce\x18\x05 \x01(\fR\fsessionNonce\"C\n" +
	"\vPlayerReady\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x19\n" +
	"\bhand_num\x18\x02 \x01(\x03R\ahandNum\"\xc8\x01\n" +
	"\vShuffleStep\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x19\n" +
	"\bhand_num\x18\x02 \x01(\x03R\ahandNum\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04deck\x18\x04 \x03(\fR\x04deck\x12'\n" +
	"\x0fcommitment_hash\x18\x05 \x01(\fR\x0ecommitmentHash\x12)\n" +
	"\x10commitment_nonce\x18\x06 \x01(\fR\x0fcommitmentNonce\"\x8b\x01\n" +
	"\rShuffleCommit\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x19\n" +
	"\bhand_num\x18\x02 \x01(\x03R\ahandNum\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\tR\bplayerId\x12'\n" +
	"\x0fcommitment_hash\x18\x04 \x01(\fR\x0ecommitmentHash\"E\n" +
	"\vZKProofWire\x12\f\n" +
	"\x01a\x18\x01 \x01(\fR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\fR\x01b\x12\f\n" +
	"\x01s\x18\x03 \x01(\fR\x01s\x12\f\n" +
	"\x01h\x18\x04 \x01(\fR\x01h\"\xe6\x01\n" +
	"\x0ePartialDecrypt\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x19\n" +
	"\bhand_num\x18\x02 \x01(\x03R\ahandNum\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\tR\bplayerId\x12\x1d\n" +
	"\n" +
	"card_index\x18\x04 \x01(\x05R\tcardIndex\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x05 \x01(\fR\n" +
	"ciphertext\x12\x16\n" +
	"\x06result\x18\x06 \x01(\fR\x06result\x12*\n" +
	"\x05proof\x18\a \x01(\v2\x14.network.ZKProofWireR\x05proof\"\xa3\x01\n" +
	"\fPlayerAction\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x19\n" +
	"\bhand_num\x18\x02 \x01(\x03R\ahandNum\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\x05R\x06action\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x03R\x03seq\"\xf1\x01\n" +
	"\rGameStateSync\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x19\n" +
	"\bhand_num\x18\x02 \x01(\x03R\ahandNum\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\x05R\x05phase\x12\x10\n" +
	"\x03pot\x18\x04 \x01(\x03R\x03pot\x12\x1f\n" +
	"\vcurrent_bet\x18\x05 \x01(\x03R\n" +
	"currentBet\x12#\n" +
	"\raction_player\x18\x06 \x01(\tR\factionPlayer\x12\x1d\n" +
	"\n" +
	"state_root\x18\a \x01(\fR\tstateRoot\x12\x1d\n" +
	"\n" +
	"action_log\x18\b \x03(\fR\tactionLog\"S\n" +
	"\tHeartbeat\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x19\n" +
	"\bhand_num\x18\x02 \x01(\x03R\ahandNum\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\"\x99\x01\n" +
	"\vTimeoutVote\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x19\n" +
	"\bhand_num\x18\x02 \x01(\x03R\ahandNum\x12(\n" +
	"\x10voting_player_id\x18\x03 \x01(\tR\x0evotingPlayerId\x12*\n" +
	"\x11timeout_player_id\x18\x04 \x01(\tR\x0ftimeoutPlayerId\"\x89\x01\n" +
	"\n" +
	"HandResult\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x19\n" +
	"\bhand_num\x18\x02 \x01(\x03R\ahandNum\x12&\n" +
	"\x04pots\x18\x03 \x03(\v2\x12.network.PotResultR\x04pots\x12\x1d\n" +
	"\n" +
	"state_root\x18\x04 \x01(\fR\tstateRoot\"B\n" +
	"\tPotResult\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1d\n" +
	"\n" +
	"winner_ids\x18\x02 \x03(\tR\twinnerIds*\xde\x01\n" +
	"\aMsgType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"JOIN_TABLE\x10\x01\x12\x10\n" +
	"\fPLAYER_READY\x10\x02\x12\x10\n" +
	"\fSHUFFLE_STEP\x10\x03\x12\x12\n" +
	"\x0eSHUFFLE_COMMIT\x10\x04\x12\x13\n" +
	"\x0fPARTIAL_DECRYPT\x10\x05\x12\x11\n" +
	"\rPLAYER_ACTION\x10\x06\x12\x13\n" +
	"\x0fGAME_STATE_SYNC\x10\a\x12\r\n" +
	"\tHEARTBEAT\x10\b\x12\x10\n" +
	"\fTIMEOUT_VOTE\x10\t\x12\x0f\n" +
	"\vHAND_RESULT\x10\n" +
	"\x12\x0f\n" +
	"\vLEAVE_TABLE\x10\vBBZ@github.com/RedPaladin7/DecentralizedPokerEngine/internal/networkb\x06proto3"

var (
	file_internal_network_messages_proto_rawDescOnce sync.Once
	file_internal_network_messages_proto_rawDescData []byte
)

func file_internal_network_messages_proto_rawDescGZIP() []byte {
	file_internal_network_messages_proto_rawDescOnce.Do(func() {
		file_internal_network_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_network_messages_proto_rawDesc), len(file_internal_network_messages_proto_rawDesc)))
	})
	return file_internal_network_messages_proto_rawDescData
}

var file_internal_network_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_network_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_network_messages_proto_goTypes = []any{
	(MsgType)(0),           // 0: network.MsgType
	(*Envelope)(nil),       // 1: network.Envelope
	(*JoinTable)(nil),      // 2: network.JoinTable
	(*PlayerReady)(nil),    // 3: network.PlayerReady
	(*ShuffleStep)(nil),    // 4: network.ShuffleStep
	(*ShuffleCommit)(nil),  // 5: network.ShuffleCommit
	(*ZKProofWire)(nil),    // 6: network.ZKProofWire
	(*PartialDecrypt)(nil), // 7: network.PartialDecrypt
	(*PlayerAction)(nil),   // 8: network.PlayerAction
	(*GameStateSync)(nil),  // 9: network.GameStateSync
	(*Heartbeat)(nil),      // 10: network.Heartbeat
	(*TimeoutVote)(nil),    // 11: network.TimeoutVote
	(*HandResult)(nil),     // 12: network.HandResult
	(*PotResult)(nil),      // 13: network.PotResult
}
var file_internal_network_messages_proto_depIdxs = []int32{
	0,  // 0: network.Envelope.type:type_name -> network.MsgType
	6,  // 1: network.PartialDecrypt.proof:type_name -> network.ZKProofWire
	13, // 2: network.HandResult.pots:type_name -> network.PotResult
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_network_messages_proto_init() }
func file_internal_network_messages_proto_init() {
	if File_internal_network_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_network_messages_proto_rawDesc), len(file_internal_network_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_network_messages_proto_goTypes,
		DependencyIndexes: file_internal_network_messages_proto_depIdxs,
		EnumInfos:         file_internal_network_messages_proto_enumTypes,
		MessageInfos:      file_internal_network_messages_proto_msgTypes,
	}.Build()
	File_internal_network_messages_proto = out.File
	file_internal_network_messages_proto_goTypes = nil
	file_internal_network_messages_proto_depIdxs = nil
}
