package config

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

type Config struct {
	PlayerName string `yaml:"player_name"`
	DataDir string `yaml:"data_dir"`
	Network NetworkConfig `yaml:"network"`
	Game GameConfig `yaml:"game"`
	Fault FaultConfig `yaml:"fault"`
	Chain ChainConfig `yaml:"chain"`
}

type NetworkConfig struct {
	ListenAddr string `yaml:"listen_addr"`
	BootstrapPeers []string `yaml:"bootstrap_peers"`
	EnableMDNS bool `yaml:"enable_mdns"`
	MaxPeers int `yaml:"max_peers"`
}

type GameConfig struct {
	TableID string `yaml:"table_id"`
	MaxSeats int `yaml:"max_seats"`
	SmallBlind int64 `yaml:"small_blind"`
	BigBlind int64 `yaml:"big_blind"`
	BuyIn int64 `yaml:"buy_in"`
	ActionTimeout time.Duration `yaml:"action_timeout"`
}

type FaultConfig struct {
	HeartbeatInterval time.Duration `yaml:"heartbeat_interval"`
	HeartbeatTimeout time.Duration `yaml:"heartbeat_timeout"`
	VoteExpiry time.Duration `yaml:"vote_expiry"`
}

type ChainConfig struct {
	Enabled bool `yaml:"enabled"`
	RPCURL string `yaml:"rpc_url"`
	ContractAddress string `yaml:"contact_address"`
	ChainID int64 `yaml:"chain_id"`
	BuyInWei string `yaml:"buy_in_wei"`
	GasLimit uint64 `yaml:"gas_limit"`
	PrivateKeyHex string `yaml:"private_key_hex"` 
}

func Default() *Config {
	home, _ := os.UserHomeDir()
	return &Config{
		PlayerName: "Player",
		DataDir: filepath.Join(home, ".poker"),
		Network: NetworkConfig{
			ListenAddr: "/ip4/0.0.0.0/tcp/9000",
			EnableMDNS: true,
			MaxPeers: 20,
		},
		Game: GameConfig{
			TableID: "default-table",
			MaxSeats: 6,
			SmallBlind: 5,
			BigBlind: 10,
			BuyIn: 1000,
			ActionTimeout: 45 * time.Second,
		}, 
		Fault: FaultConfig{
			HeartbeatInterval: 5 * time.Second,
			HeartbeatTimeout: 15 * time.Second,
			VoteExpiry: 30 * time.Second,
		},
		Chain: ChainConfig{
			Enabled: false,
			RPCURL: "http://127.0.0.1:8545",
			ChainID: 31337,
			GasLimit: 500_000,
		},
	}
}

func (c *Config) Validate() error {
	if c.PlayerName == "" {
		return fmt.Errorf("player_name is required")
	}
	if c.Game.MaxSeats < 2 || c.Game.MaxSeats > 9 {
		return fmt.Errorf("max_seats must be 2–9, got %d", c.Game.MaxSeats)
	}
	if c.Game.SmallBlind <= 0 {
		return fmt.Errorf("small_blind must be positive")
	}
	if c.Game.BigBlind <= 0 || c.Game.BigBlind <= c.Game.SmallBlind {
		return fmt.Errorf("big_blind must be > small_blind")
	}
	if c.Game.BuyIn < c.Game.BigBlind*10 {
		return fmt.Errorf("buy_in must be at least 10x big_blind")
	}
	if c.Chain.Enabled {
		if c.Chain.RPCURL == "" {
			return fmt.Errorf("chain.rpc_url required when chain is enabled")
		}
		if c.Chain.ContractAddress == "" {
			return fmt.Errorf("chain.contract_address required when chain is enabled")
		}
	}
	return nil
}

func (c *ChainConfig) ECDSAPrivateKey() (*ecdsa.PrivateKey, error) {
	if c.PrivateKeyHex == "" {
		return nil, nil
	}
	b, err := hex.DecodeString(c.PrivateKeyHex)
	if err != nil {
		return nil, fmt.Errorf("")
	}
	priv := new(ecdsa.PrivateKey)
	priv.Curve = elliptic.P256()
	priv.PublicKey.X, priv.PublicKey.Y = priv.Curve.ScalarBaseMult(b)
	return priv, nil
}

func GenerateECDSAKey() (*ecdsa.PrivateKey, string, error) {
	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, "", fmt.Errorf("")
	}
	hexKey := hex.EncodeToString(priv.D.Bytes())
	return priv, hexKey, nil
}

func (c *Config) EnsureDataDir() error {
	return os.MkdirAll(c.DataDir, 0o700)
}

func (c *Config) IdentityKeyPath() string {
	return filepath.Join(c.DataDir, "identity.key")
}

func (c *Config) LoadIdentityKey() ([]byte, error) {
	path := c.IdentityKeyPath()
	b, err := os.ReadFile(path)
	if err == nil && len(b) == 64 {
		return b, nil
	}
	seed := make([]byte, 64)
	if _, err := rand.Read(seed); err != nil {
		return nil, fmt.Errorf("")
	}
	if err := c.EnsureDataDir(); err != nil {
		return nil, err
	}
	if err := os.WriteFile(path, seed, 0o600); err != nil {
		return nil, fmt.Errorf("")
	}
	return seed, nil
}
func DefaultYAML() string {
	return `# P2P Poker Node Configuration
# Generated by: poker init
 
player_name: "Player"
data_dir: "~/.poker"
 
network:
  listen_addr: "/ip4/0.0.0.0/tcp/9000"
  enable_mdns: true
  max_peers: 20
  # For internet play, add bootstrap peers:
  # bootstrap_peers:
  #   - "/ip4/1.2.3.4/tcp/9000/p2p/12D3KooW..."
 
game:
  table_id: "my-table"
  max_seats: 6
  small_blind: 5
  big_blind: 10
  buy_in: 1000
  action_timeout: 45s
 
fault:
  heartbeat_interval: 5s
  heartbeat_timeout: 15s
  vote_expiry: 30s
 
chain:
  enabled: false
  rpc_url: "http://127.0.0.1:8545"
  contract_address: ""
  chain_id: 31337
  gas_limit: 500000
  buy_in_wei: "10000000000000000"   # 0.01 ETH
  # private_key_hex: ""             # generate with: poker keygen
`
}